language: python
cache: pip
dist: xenial
python:
  - "3.7"
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - sleep 10
  - psql -c 'create database db;' -U postgres
install:
  - cat requirements/base.txt | grep "^Django==\|^psycopg2" | xargs pip install
  - pip install -r requirements/ci.txt
  - pip install awscli
script:
  - bandit -r . -ll
  - docker build -t $DOCKER_REPO .
env:
  global:
    ALLOWED_HOSTS: "*"
    CORS_ORIGIN_WHITELIST: "*"
    DATABASE_ENGINE: "postgresql"
    DATABASE_NAME: "db"
    DATABASE_USER: "root"
    DATABASE_PASSWORD: "root"
    DATABASE_HOST: "localhost"
    DATABASE_PORT: "5432"
    DOCKER_REPO: "dukaan_shop/dukaan"
    JWT_ISSUER: dukaan


deploy:
  provider: script
  script: bash scripts/deploy-aws.sh
  on:
    branch: master

