version: "3.1"

services:

  postgres_dukaan_service:
    container_name: postgres_dukaan_service
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:10.4-alpine
    environment:
      POSTGRES_DB: dukaandb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  dukaan_service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint-dev.sh
    container_name: dukaan_service
    image: dukaan_service
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres_dukaan_service
    environment:
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      CORS_ORIGIN_WHITELIST: localhost,127.0.0.1,0.0.0.0
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "dukaandb"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_dukaan_service"
      DATABASE_PORT: "5432"
      DEBUG: "True"
      SECRET_KEY: "nothing"
      STATIC_ROOT: /static/
