# Generated by Django 2.2.17 on 2021-01-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Store UUID')),
                ('name', models.CharField(max_length=125, verbose_name='Store name')),
                ('address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=10, verbose_name='City name of Store')),
                ('country', models.CharField(max_length=20, verbose_name='Store Country')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Soft delete an store ?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'ordering': ('-name',),
            },
        ),
    ]
