# Generated by Django 2.2.17 on 2021-01-11 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Identifier of each store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_link',
            field=models.CharField(max_length=255, unique=True, verbose_name='unique Store Link'),
        ),
    ]
