# Generated by Django 2.2.17 on 2021-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210111_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_link',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='unique Store Link'),
        ),
    ]
